<?php

namespace App\Services\RealEstateService;

use App\Models\Block;
use App\Services\WebsiteService\BlockService;

class CommunityService extends BlockService
{
    public function mapLocaleBlock(Block $block): array
    {
        $numberOfProjects = $block->comProjects()->count();
        $numberOfProperties = $block->comProperties()->count();
        return [
            ...parent::mapLocaleBlock($block),
            'numberOfProjects' => $numberOfProjects,
            'numberOfProperties' => $numberOfProperties,
        ]; // TODO: Change the autogenerated stub
    }

    public function getSchema(Block $block): array
    {
        return [
            parent::getSchema($block),
        ];
    }
}
