<?php

namespace App\Services\RealEstateService;

use App\Facades\FileService\UploadService;
use App\Models\Block;
use App\Models\Project;
use App\Services\RealEstateService\Filter\BlockFilter;
use App\Services\RealEstateService\Filter\CityFilter;
use App\Services\RealEstateService\Filter\CitySlugFilter;
use App\Services\RealEstateService\Filter\CommunityFilter;
use App\Services\RealEstateService\Filter\CommunitySlugFilter;
use App\Services\RealEstateService\Filter\DeveloperFilter;
use App\Services\RealEstateService\Filter\DeveloperSlugFilter;
use App\Services\RealEstateService\Filter\LimitFilter;
use App\Services\RealEstateService\Filter\OffsetFilter;
use App\Services\RealEstateService\Filter\ProjHigherPriceFilter;
use App\Services\RealEstateService\Filter\ProjLowerPriceFilter;
use App\Services\WebsiteService\BlockService;
use Carbon\Carbon;
use App\Facades\RealEstateService\LeadService;
use Illuminate\Pipeline\Pipeline;
use Illuminate\Support\Collection;

class ProjectService extends BlockService
{
    private string $qrCodeFileName = 'QRCODE';
    private string $brochureFileName = 'BROCHURE';

    protected string $fileContainer = 'project';
    public function mapBlockModel(Block $block): array
    {
        $project = $block->project()->first();
        $developerName = '';
        $communityName = '';
        $cityName = '';
        $brochure = $project->files()->where('name', $this->brochureFileName)->first();
        $brochureModel = is_null($brochure) ? null : UploadService::mapFileModel($brochure);
        $qrFile = $project->files()->where('name', $this->qrCodeFileName)->first();
        $qrFileModel = is_null($qrFile) ? null : UploadService::mapFileModel($qrFile);

        //TODO: Add Location
        if (!is_null($project)) {
            $developerName = parent::getBlockName($project->developer()->first()) ;
            $communityName = parent::getBlockName($project->community()->first());
            $cityName = parent::getBlockName($project->city()->first());
        }

        $leads = $project->leads()->orderBy('created_at', 'DESC')->get();
        $leadsCount = $leads->count();
        $leadsModel = [];
        foreach ($leads as $lead) {
            $leadsModel[] = LeadService::mapLeadModel($lead);
        }

        return [
            ...parent::mapBlockModel($block),
            'projectId' =>$project->id,
            'developerId' =>$project->developer_id,
            'communityId' =>$project->community_id,
            'cityId' =>$project->city_id,
            'developerName' => $developerName,
            'communityName' => $communityName,
            'cityName' => $cityName,
            'lunchDate' => $project->lunch_date,
            'lunchPrice' => $project->lunch_price,
            'status' => $project->status,
            'type' => $project->type,
            'downPayment' => $project->down_payment,
            'youtubeUrl' => $project->youtube_url,
            'constructionPaymentRate' => $project->construction_payment_rate,
            'handoverPaymentRate' => $project->handover_payment_rate,
            'paymentPlanType' => $project->payment_plan_type,
            'quarter' => $project->quarter,
            'handoverDate' => $project->handover_date,
            'isProjectActive' => (bool)$project->is_active,
            'brochure' => $brochureModel,
            'qrFile' => $qrFileModel,
            'leads' => $leadsModel,
            'leadsCount' => $leadsCount,

        ]; // TODO: Change the autogenerated stub
    }

    public function mapLocaleBlock(Block $block): array
    {
        $project = $block->project()->first();
        $developerName = '';
        $communityName = '';
        $cityName = '';
        if (!is_null($project)) {
            $developerName = parent::getBlockName($project->developer()->first()) ;
            $communityName = parent::getBlockName($project->community()->first());
            $cityName = parent::getBlockName($project->city()->first());
        }

        $brochure = $project->files()->where('name', $this->brochureFileName)->first();
        $brochureModel = is_null($brochure) ? null : UploadService::mapFileModel($brochure);
        $qrFile = $project->files()->where('name', $this->qrCodeFileName)->first();
        $qrFileModel = is_null($qrFile) ? null : UploadService::mapFileModel($qrFile);
//        $parentBlock = parent::mapLocaleBlock($block);
        return [
            ...parent::mapLocaleBlock($block),
            'projectId' =>$project->id,
            'developerId' =>$project->developer_id,
            'communityId' =>$project->community_id,
            'cityId' =>$project->city_id,
            'developerName' => $developerName,
            'communityName' => $communityName,
            'cityName' => $cityName,
            'lunchDate' => Carbon::make($project->lunch_date)->format('Y M-d'),
            'lunchPrice' => $project->lunch_price,
            'status' => $project->status,
            'type' => $project->type,
            'qrCode' => $project->qr_code,
            'brochureUrl' => $project->brochure_url,
            'downPayment' => $project->down_payment,
            'youtubeUrl' => $project->youtube_url,
            'constructionPaymentRate' => $project->construction_payment_rate,
            'handoverPaymentRate' => $project->handover_payment_rate,
            'paymentPlanType' => $project->payment_plan_type,
            'quarter' => $project->quarter,
            'handoverDate' => Carbon::make($project->handover_date)->format('Y M-d'),
            'brochure' => $brochureModel,
            'qrFile' => $qrFileModel,

        ]; // TODO: Change the autogenerated stub
    }

    private function fillProjectForm(Project &$project, int $blockId): void
    {
        $data = request()->all();
        $project->fill([
            'block_id' => $blockId,
            'developer_id' => $data['developerId'],
            'community_id' => $data['communityId'],
            'city_id' => $data ['cityId'],
            'lunch_date' => Carbon::make($data['lunchDate']),
            'lunch_price' => $data['lunchPrice'],
            'status' => $data['status'],
            'type' => $data['type'],
            'is_active' => $data['isActive'] === 'true',
            'qr_code' => $data['qrCodeUrl'] ?? null,
            'brochure_url' => $data['brochureUrl'] ?? null,
            'down_payment' => $data['downPayment'] ?? null,
            'youtube_url' => $data['youtubeUrl'] ?? null,
            'construction_payment_rate' => $data['constructionPaymentRate'] ?? null,
            'handover_payment_rate' => $data['handoverPaymentRate'] ?? null,
            'payment_plan_type' => $data['paymentPlanType'],
            'quarter' => $data['quarter'],
            'handover_date' => Carbon::make($data['handoverDate']),
        ]);
    }

    public function storeBlock($data): array
    {
//        dd($data);
        $block = new Block();
        $this->fillBlockForm($block);
        $block->save();
        //Store Translations:
        $this->storeTranslations($data, $block);
        //Store Files:
        //        2. Store File:
        if (array_key_exists('image', $data)) {
            $data['refId'] = $block->id;
            $data['refType'] = $this->reference;
            UploadService::saveFile($data, 'image', 'block');
        }

        //Store Brochure:

        $project = new Project();
        $this->fillProjectForm($project, $block->id);
        $project->save();

        if (array_key_exists('qrCode', $data)) {
            $data['name'] = $this->qrCodeFileName;
            $data['refId'] = $project->id;
            $data['refType'] = Project::class;
            UploadService::saveFile($data, 'qrCode', 'project');
        }

        if (array_key_exists('brochure', $data)) {
            $data['name'] = $this->brochureFileName;
            $data['refId'] = $project->id;
            $data['refType'] = Project::class;
            $data['isImage'] = 'false';
            UploadService::saveFile($data, 'brochure', 'project');
        }

        return $this->mapBlockModel($block);
    }

    public function updateTranslations($data, Block $block): ?Block
    {
        parent::updateTranslations($data, $block);
        $project = $block->project()->first();
        if (is_null($project)) {
            return null;
        }
        $this->fillProjectForm($project, $block->id);
        $project->update();
        return Block::query()->where('id', $block->id)->first();
    }

    public function deleteBlock(Block $block): void
    {
        $project = $block->project()->first();
        $files = $project->files()->get();

        foreach ($files as $file) {
            UploadService::deleteFile($file->id, 'project');
        }
        parent::deleteBlock($block);

    }

    public function deleteImage(Array $data, Block $block): array
    {
        UploadService::deleteFile($data['imageId'], $this->fileContainer);
        return $this->mapBlockModel($block);
    }

    public function updateImage(array $data, Block $block): array
    {
        $file = $block->project()->first()->files()->where('id', $data['imageId'])->first();
//        $image = $block->images()->where('id', $data['imageId'])->first();
        if (array_key_exists('qrCode', $data)) {
//            $data['name'] = $this->qrCodeFileName;
            request()->merge(['name' => $this->qrCodeFileName]);
            UploadService::updateFile($file->id, 'qrCode', 'project');
        }

        if (array_key_exists('brochure', $data)) {
            request()->merge(['name' => $this->brochureFileName]);
            UploadService::updateFile($file->id, 'brochure', 'project');
        }

        return $this->mapBlockModel($block);
    }

    public function saveImage(array $data, Block $block): array
    {
        $project = $block->project()->first();
        if (array_key_exists('qrCode', $data)) {
            $data['name'] = $this->qrCodeFileName;
            $data['refId'] = $project->id;
            $data['refType'] = Project::class;
            UploadService::saveFile($data, 'qrCode', 'project');
        }

        if (array_key_exists('brochure', $data)) {
            $data['name'] = $this->brochureFileName;
            $data['refId'] = $project->id;
            $data['refType'] = Project::class;
            $data['isImage'] = 'false';
            UploadService::saveFile($data, 'brochure', 'project');
        }

        return $this->mapBlockModel($block);
    }

    public function getActiveBlocks($category): array
    {
        $projects = app(Pipeline::class)
            ->send(Project::query())
            ->through([
                BlockFilter::class,
                CityFilter::class,
                CitySlugFilter::class,
                CommunityFilter::class,
                CommunitySlugFilter::class,
                DeveloperFilter::class,
                DeveloperSlugFilter::class,
                LimitFilter::class,
                OffsetFilter::class,
                ProjLowerPriceFilter::class,
                ProjHigherPriceFilter::class,
            ])
            ->then(function ($models) use ($category) {
                return $models
                    ->whereHas('block', function ($query) use ($category) {
                    $query
                        ->where('category', $category)
                        ->where('is_active', 1);
                });
            })->get();

        $rawBlocks = new Collection();
        foreach ($projects as $project) {
            $rawBlocks->push($project->block);
        }

        $rawBlocks = $rawBlocks
            ->sortBy('order')
            ->sortByDesc('start_date')
        ->values();

        $blocks = [];
        foreach ($rawBlocks as $block) {
            $blocks[] = $this->mapLocaleBlock($block);
        }

        return $blocks;

    }

    public function getSchema(Block $block): array
    {
        $project = $this->mapLocaleBlock($block);
        return [
            ...parent::getSchema($block),
            "url" => route('projects.show', $project['slug']),
            "address" => [
                "@type" => "PostalAddress",
                "addressLocality" => $project['communityName'],
                "addressRegion" => $project['cityName'],
                "addressCountry" => "UAE",
            ],
            "status" => $project['status'],
            "launchDate" => $project['lunchDate'],
            "launchPrice" => $project['lunchPrice'],
            "type" => $project['type'],
            "downPayment" => $project['downPayment'],
            "paymentPlanType" => $project['paymentPlanType'],
            "quarter" => $project['quarter'],
            "handoverDate" => $project['handoverDate'],
        ];
    }
}
