<?php

namespace App\Services\RealEstateService;

use App\Facades\FileService\UploadService;
use App\Facades\RealEstateService\LeadService;
use App\Models\Block;
use App\Models\Project;
use App\Models\Property;
use App\Services\RealEstateService\Filter\BlockFilter;
use App\Services\RealEstateService\Filter\CityFilter;
use App\Services\RealEstateService\Filter\CitySlugFilter;
use App\Services\RealEstateService\Filter\CommunityFilter;
use App\Services\RealEstateService\Filter\CommunitySlugFilter;
use App\Services\RealEstateService\Filter\DeveloperFilter;
use App\Services\RealEstateService\Filter\DeveloperSlugFilter;
use App\Services\RealEstateService\Filter\LimitFilter;
use App\Services\RealEstateService\Filter\OffsetFilter;
use App\Services\RealEstateService\Filter\ProjHigherPriceFilter;
use App\Services\RealEstateService\Filter\ProjLowerPriceFilter;
use App\Services\RealEstateService\Filter\PropHigherPriceFilter;
use App\Services\RealEstateService\Filter\PropLowerPriceFilter;
use App\Services\WebsiteService\BlockService;
use Carbon\Carbon;
use Illuminate\Pipeline\Pipeline;
use Illuminate\Support\Collection;

class PropertyService extends BlockService{

    private string $qrCodeFileName = 'QRCODE';
    private string $brochureFileName = 'BROCHURE';

    protected string $fileContainer = 'property';
    public function mapBlockModel(Block $block): array
    {
        $property = $block->property()->first();
        $developerName = '';
        $communityName = '';
        $cityName = '';
        $brochure = $property->files()->where('name', $this->brochureFileName)->first();
        $brochureModel = is_null($brochure) ? null : UploadService::mapFileModel($brochure);
        $qrFile = $property->files()->where('name', $this->qrCodeFileName)->first();
        $qrFileModel = is_null($qrFile) ? null : UploadService::mapFileModel($qrFile);
        //TODO: Add Location
        if (!is_null($property)) {
            $developerName = parent::getBlockName($property->developer()->first()) ;
            $communityName = parent::getBlockName($property->community()->first());
            $cityName = parent::getBlockName($property->city()->first());
        }

        $leads = $property->leads()->orderBy('created_at', 'DESC')->get();
        $leadsCount = $leads->count();
        $leadsModel = [];
        foreach ($leads as $lead) {
            $leadsModel[] = LeadService::mapLeadModel($lead);
        }

        return [
            ...parent::mapBlockModel($block),
            'propertyId' => $property->id,
            'developerId' =>$property->developer_id,
            'communityId' =>$property->community_id,
            'cityId' =>$property->city_id,
            'developerName' => $developerName,
            'communityName' => $communityName,
            'cityName' => $cityName,
            'features' => $property->features,
            'status' => $property->status,
            'price' => $property->price,
            'area' => $property->area,
            'numberOfBeds' => $property->number_of_beds,
            'isPropertyActive' => (bool)$property->is_active,
            'brochure' => $brochureModel,
            'qrFile' => $qrFileModel,
            'leads' => $leadsModel,
            'leadsCount' => $leadsCount,

        ]; // TODO: Change the autogenerated stub
    }

    public function mapLocaleBlock(Block $block): array
    {
        $property = $block->property()->first();
        $developerName = '';
        $communityName = '';
        $cityName = '';
        $brochure = $property->files()->where('name', $this->brochureFileName)->first();
        $brochureModel = is_null($brochure) ? null : UploadService::mapFileModel($brochure);
        $qrFile = $property->files()->where('name', $this->qrCodeFileName)->first();
        $qrFileModel = is_null($qrFile) ? null : UploadService::mapFileModel($qrFile);
        if (!is_null($property)) {
            $developerName = parent::getBlockName($property->developer()->first()) ;
            $communityName = parent::getBlockName($property->community()->first());
            $cityName = parent::getBlockName($property->city()->first());
        }
        return [
            ...parent::mapLocaleBlock($block),
            'propertyId' => $property->id,
            'developerId' =>$property->developer_id,
            'communityId' =>$property->community_id,
            'cityId' =>$property->city_id,
            'developerName' => $developerName,
            'communityName' => $communityName,
            'cityName' => $cityName,
            'features' => $property->features,
            'status' => $property->status,
            'price' => $property->price,
            'area' => $property->area,
            'numberOfBeds' => $property->number_of_beds,
            'isPropertyActive' => (bool)$property->is_active,
            'brochure' => $brochureModel,
            'qrFile' => $qrFileModel,

        ]; // TODO: Change the autogenerated stub
    }

    private function fillPropertyForm(Property &$property, int $blockId): void
    {
        $data = request()->all();
        $property->fill([
            'block_id' => $blockId,
            'developer_id' => $data['developerId'],
            'community_id' => $data['communityId'],
            'city_id' => $data ['cityId'],
            'features' => $data['features'] ?? null,
            'status' => $data['status'],
            'price' => $data['price'],
            'area' => $data['area'],
            'number_of_beds' => $data['numberOfBeds'],
            'is_active' => $data['isActive'] === 'true',
        ]);
    }

    public function storeBlock($data): array
    {
//        dd($data);
        $block = new Block();
        $this->fillBlockForm($block);
        $block->save();
        //Store Translations:
        $this->storeTranslations($data, $block);
        //Store Files:
        //        2. Store File:
        if (array_key_exists('image', $data)) {
            $data['refId'] = $block->id;
            $data['refType'] = $this->reference;
            UploadService::saveFile($data, 'image', 'block');
        }

        $property = new Property();
        $this->fillPropertyForm($property, $block->id);
        $property->save();
        return $this->mapBlockModel($block);
    }

    public function updateTranslations($data, Block $block): ?Block
    {
        parent::updateTranslations($data, $block);
        $property = $block->property()->first();
        if (is_null($property)) {
            return null;
        }
        $this->fillPropertyForm($property, $block->id);
        $property->update();
        return Block::query()->where('id', $block->id)->first();
    }

    public function deleteImage(Array $data, Block $block): array
    {
        UploadService::deleteFile($data['imageId'], $this->fileContainer);
        return $this->mapBlockModel($block);
    }

    public function updateImage(array $data, Block $block): array
    {
        $file = $block->property()->first()->files()->where('id', $data['imageId'])->first();
//        $image = $block->images()->where('id', $data['imageId'])->first();
        if (array_key_exists('qrCode', $data)) {
//            $data['name'] = $this->qrCodeFileName;
            request()->merge(['name' => $this->qrCodeFileName]);
            UploadService::updateFile($file->id, 'qrCode', 'property');
        }

        if (array_key_exists('brochure', $data)) {
            request()->merge(['name' => $this->brochureFileName]);
            UploadService::updateFile($file->id, 'brochure', 'property');
        }

        return $this->mapBlockModel($block);
    }

    public function saveImage(array $data, Block $block): array
    {
        $property = $block->property()->first();
        if (array_key_exists('qrCode', $data)) {
            $data['name'] = $this->qrCodeFileName;
            $data['refId'] = $property->id;
            $data['refType'] = Property::class;
            UploadService::saveFile($data, 'qrCode', 'property');
        }

        if (array_key_exists('brochure', $data)) {
            $data['name'] = $this->brochureFileName;
            $data['refId'] = $property->id;
            $data['refType'] = Property::class;
            $data['isImage'] = 'false';
            UploadService::saveFile($data, 'brochure', 'property');
        }

        return $this->mapBlockModel($block);
    }

    public function getActiveBlocks($category): array
    {
        $properties = app(Pipeline::class)
            ->send(Property::query())
            ->through([
                BlockFilter::class,
                CityFilter::class,
                CitySlugFilter::class,
                CommunityFilter::class,
                CommunitySlugFilter::class,
                DeveloperFilter::class,
                DeveloperSlugFilter::class,
                LimitFilter::class,
                OffsetFilter::class,
                PropLowerPriceFilter::class,
                PropHigherPriceFilter::class,
            ])
            ->then(function ($models) use ($category) {
                return $models->whereHas('block', function ($query) use ($category) {
                    $query
                        ->where('category', $category)
                        ->where('is_active', 1);
                });
            })->get();

        $rawBlocks = new Collection();
        foreach ($properties as $property) {
            $rawBlocks->push($property->block);
        }

        $rawBlocks = $rawBlocks
            ->sortBy('order')
            ->sortByDesc('start_date')
            ->values();

        $blocks = [];
        foreach ($rawBlocks as $block) {
            $blocks[] = $this->mapLocaleBlock($block);
        }

        return $blocks;

    }

    public function getSchema(Block $block): array
    {
        $property = $this->mapLocaleBlock($block);
        return [
            ...parent::getSchema($block),
            "address" => [
                "@type" => "PostalAddress",
                "addressLocality" => $property['communityName'],
                "addressRegion" => $property['cityName'],
                "addressCountry" => "UAE",
                "developer" => $property['developerName'],
            ],
//            "numberOfRooms" => $property['numberOfRoom'],
            "features" => $property['features'],
            "status" => $property['status'],
            "price" => $property['price'],
            "area" => $property['area'],
            "numberOfBeds" => $property['numberOfBeds'],
            "floorSize" => [
                "@type" => "QuantitativeValue",
                "value" => $property['area'],
                "unitCode" => "MTR",
            ],
            "url" => route('properties.show', $property['slug']),

        ];
    }
}
