<?php

namespace App\Facades\RealEstateService;

use Illuminate\Support\Facades\Facade;

class CommunityService extends Facade
{
    protected static function getFacadeAccessor()
    {
        return 'CommunityService';
//        parent::getFacadeAccessor(); // TODO: Change the autogenerated stub
    }
}
