<?php

namespace App\Facades\WebsiteService;

use App\Models\Contact;
use Illuminate\Support\Facades\Facade;


/**
 * @method static array mapContact(Contact $contact);
 * @method static void storeContact(array $data);
 * @method static array getContacts()
 * @method static array getContact(Contact $contact)
 * @method static void deleteContact(Contact $contact)
 * @method static int getCount()
 */
class ContactService extends Facade
{
    protected static function getFacadeAccessor(): string
    {
        return 'ContactService';
//        parent::getFacadeAccessor(); // TODO: Change the autogenerated stub
    }
}
